In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_excel('fruit.xlsx')

In [3]:
dataset.head()

diameter  weight  red  green  blue    name
0      2.96   86.76  172     85     2  orange
1      3.91   88.05  166     78     3  orange
2      4.42   95.17  156     81     2  orange
3      4.47   95.60  163     81     4  orange
4      4.48   95.76  161     72     9  orange

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   diameter  10000 non-null  float64
 1   weight    10000 non-null  float64
 2   red       10000 non-null  int64  
 3   green     10000 non-null  int64  
 4   blue      10000 non-null  int64  
 5   name      10000 non-null  object 
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [5]:
dataset.empty

False

In [7]:
en = LabelEncoder()

dataset['name'] = en.fit_transform(dataset['name'])
dataset.head()

diameter  weight  red  green  blue  name
0      2.96   86.76  172     85     2     1
1      3.91   88.05  166     78     3     1
2      4.42   95.17  156     81     2     1
3      4.47   95.60  163     81     4     1
4      4.48   95.76  161     72     9     1

In [8]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
x

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [10]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 123)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  7500
x_test =  2500
y_train =  7500
y_test =  2500


In [13]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
x_train

array([[ 1.38783323,  1.39661638, -0.46554288, -0.34858931,  1.39603808],
       [-0.0376021 , -0.00574644,  0.20264568,  1.88002338, -1.03014089],
       [-1.57071419, -1.53491321,  0.10719017, -1.29146391, -1.03014089],
       ...,
       [-0.30935775, -0.38205681,  0.58446771, -0.34858931,  0.29322946],
       [-1.15538951, -1.16441326,  0.67992322,  1.10858052, -0.47873658],
       [-0.41190705, -0.39743735,  0.77537873,  1.88002338, -1.03014089]])

In [15]:
x_test

array([[-0.71955497, -0.7282897 , -1.03827592, -0.00572582, -1.03014089],
       [-1.63224377, -1.62890535,  0.67992322,  0.93714878, -0.80957916],
       [ 1.58780437,  1.59827225,  0.87083423, -0.77716867,  0.51379119],
       ...,
       [-1.11949725, -1.12134777, -1.61100897,  2.39431862,  0.95491464],
       [ 0.02392749,  0.04278769,  2.30266685,  1.1942964 ,  0.1829486 ],
       [-0.80159441, -0.79596405,  0.87083423,  0.07999005, -1.03014089]])

In [16]:
y_train

array([0, 1, 1, ..., 0, 1, 1])

In [17]:
y_test

array([1, 1, 0, ..., 1, 1, 1])

In [18]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [19]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [20]:
classifier.predict_proba(x_test)

array([[3.01566739e-03, 9.96984333e-01],
       [3.91372112e-07, 9.99999609e-01],
       [9.99997251e-01, 2.74948723e-06],
       ...,
       [1.40928948e-04, 9.99859071e-01],
       [5.95102985e-02, 9.40489702e-01],
       [4.56254133e-04, 9.99543746e-01]])

In [21]:
 cm = confusion_matrix(y_test, y_pred)
 print(cm)

[[1159   99]
 [  92 1150]]


In [23]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.93      0.92      0.92      1258
           1       0.92      0.93      0.92      1242

    accuracy                           0.92      2500
   macro avg       0.92      0.92      0.92      2500
weighted avg       0.92      0.92      0.92      2500



In [26]:
akurasi = accuracy_score(y_test, y_pred)
print("Tingkat Akurasi : %d persen"%(akurasi*100))

Tingkat Akurasi : 92 persen
